name: Generate Snake

# Controls when the action will run
on:
  # Run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3
      
      # Generate the snake game from github user contributions
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Belalgrd
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Push the generated files to the output branch
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
